#!/bin/bash
####################################################################################################
##  @file
##  
##  @brief          Bash Doxgen Unit Test
##  
##  @note           -*- tab-width: 4; encoding: utf-8 -*-
## 
##  @author         Damien Nadé <bash-argsparse@livna.org>
## 
##  @copyright      WTFPLv2
##  
##  @version        1
####################################################################################################

declare -r readonly
declare -r assigned_readonly=readonly-value
declare -a array
declare -a assigned_array=(1 2)
declare -A associative_array
declare -A assigned_associative_array=([x]=1 [y]=2)
declare -i integer
declare -i assigned_integer=2
declare -x declared_exported
declare -x assigned_declared_exported=1

declare -ri readonly_integer
declare -ri assigned_readonly_integer=2

declare -rix readonly_exported_integer
declare -rix assigned_readonly_exported_integer=3

declare -rA readonly_associative_array
declare -rA assigned_readonly_associative_array=([a]=2 [b]=3)

declare -l lowercase
declare -l assigned_lowercase=l

declare -u uppercase
declare -u assigned_uppercase=U

export exported
export assigned_exported=1

####################################################################################################
## @fn function_1()
## @brief 1st function
## @param param1 first parameter
##
## Don't skip empty line above
####################################################################################################
function_1() {
    bogus
    bogus2;
}

####################################################################################################
## @fn function_2a()
## @brief 2nd function
## @param param1 first parameter
## @param[in] param2 second parameter
## @param[in] param3 third parameter
####################################################################################################
function function_2a() {
    bogus
    bogus2;
}

    ####################################################################################################
    ## @fn function_2b()
    ## @brief 2nd function
    ## @param param1 first parameter
    ## @param[in] param2 second parameter
    ## @param[in] param3 third parameter
    ####################################################################################################
    function function_2b() {
        bogus
        bogus2;
    }

####################################################################################################
## @fn function_3()
## 
##  @brief          2nd function
##  
##  @param[in]      param1              first parameter
##  @param[out]     param2              second parameter
##  @param[in]      param3              third parameter
##  @param[out]     param4              fourth parameter
##  @param[in,out]  param4              fifth parameter
##  
##  @returns        Values out to user
##  
##  @retval         1                   Return value of 1
##  @retval         2                   Return value of 2
####################################################################################################
function function_3() {
    bogus
    bogus2;
}


